defaults: &defaults
  adapter: mongodb
  host: localhost
  port: 27017
  
development:
  <<: *defaults
  database: clock_development
  
test:
  <<: *defaults
  database: clock_test
  
production:
  <<: *defaults
  database: clock_production
