development:
  sessions:
    default:
      database: clock_development
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: clock_test
      hosts:
        - localhost:27017

production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
  options:
    identity_map_enabled: true
    preload_models:
      - Marquee
      - Notice
      - Period
      - Schedule
      - Theme
    use_activesupport_time_zone: true
