defaults: &defaults
  adapter: mongodb
  
development:
  <<: *defaults
  host: localhost
  database: clock_development
  port: 27017
  
test:
  <<: *defaults
  host: localhost
  database: clock_test
  port: 27017
  
production:
  <<: *defaults
  database: clock_production
  hosts:
  - - localhost
    - nil
  - - staff.mongohq.com
    - 10015
  
heroku:
  <<: *defaults
  host: staff.mongohq.com
  database: clock_production
  port: 10055
  username: ENV["MONGOHQ_USERNAME"]
  password: ENV["MONGOHQ_PASSWORD"]
